[package]
name = "challenge"
edition = "2024.beta"
published-at = "0x681c6cf2f87e99b24096e64feece5a5f3b12d730a1f0c63b2c1dde7e700a5738"

[dependencies]

[addresses]
challenge = "0x681c6cf2f87e99b24096e64feece5a5f3b12d730a1f0c63b2c1dde7e700a5738"
